import React, { useState, useMemo } from 'react';
import { useLiveQuery } from 'dexie-react-hooks';
import { db } from '../lib/db';
import { formatCurrency } from '../lib/utils';
import { useStoreContext } from '../lib/StoreContext';
import { Link } from 'react-router-dom';
import { Wallet, ArrowUpRight, ArrowDownRight, Calendar, Search, Edit2, Save, X, ExternalLink, Banknote, CreditCard, Lock } from 'lucide-react';
import { useAuth } from '../lib/AuthContext';

export default function Treasury() {
  const { user } = useAuth();
  const isGuest = user?.role === 'guest';
  const { activeStoreId } = useStoreContext();
  const [dateRange, setDateRange] = useState({
    start: new Date(new Date().setMonth(new Date().getMonth() - 1)).toISOString().split('T')[0],
    end: new Date().toISOString().split('T')[0]
  });

  const [isEditingCapital, setIsEditingCapital] = useState(false);
  const [newCapitalCash, setNewCapitalCash] = useState('');
  const [newCapitalTransfer, setNewCapitalTransfer] = useState('');

  const treasuryRecord = useLiveQuery(
    () => activeStoreId ? db.treasury.where({ storeId: activeStoreId }).first() : undefined,
    [activeStoreId]
  );

  const transactions = useLiveQuery(() => db.transactions.toArray());
  const expenses = useLiveQuery(() => db.expenses.toArray());
  const purchases = useLiveQuery(() => db.purchases.toArray());

  const handleSaveCapital = async () => {
    if (!activeStoreId) return;
    const cash = parseFloat(newCapitalCash) || 0;
    const transfer = parseFloat(newCapitalTransfer) || 0;
    const total = cash + transfer;

    if (treasuryRecord) {
      await db.treasury.update(treasuryRecord.id!, { 
        initialCapital: total,
        initialCapitalCash: cash,
        initialCapitalTransfer: transfer
      });
    } else {
      await db.treasury.add({
        storeId: activeStoreId,
        date: new Date().toISOString(),
        initialCapital: total,
        initialCapitalCash: cash,
        initialCapitalTransfer: transfer
      });
    }
    setIsEditingCapital(false);
  };

  const startEditing = () => {
    setNewCapitalCash((treasuryRecord?.initialCapitalCash ?? treasuryRecord?.initialCapital ?? 0).toString());
    setNewCapitalTransfer((treasuryRecord?.initialCapitalTransfer ?? 0).toString());
    setIsEditingCapital(true);
  };

  const history = useMemo(() => {
    if (!activeStoreId || !transactions || !expenses || !purchases) return [];

    const start = new Date(dateRange.start);
    start.setHours(0, 0, 0, 0);
    const end = new Date(dateRange.end);
    end.setHours(23, 59, 59, 999);

    const items: { id: number, date: string, type: string, description: string, amount: number, isIncome: boolean, paymentMethod: 'cash' | 'transfer', link: string }[] = [];

    // Add Sales
    transactions.filter(t => t.fromStoreId === activeStoreId && t.type === 'sale').forEach(t => {
      const tDate = new Date(t.date);
      if (tDate >= start && tDate <= end) {
        if (t.cashAmount && t.cashAmount > 0) {
          items.push({
            id: t.id!,
            date: t.date,
            type: 'Venta',
            description: `Venta en efectivo #${t.id}`,
            amount: t.cashAmount,
            isIncome: true,
            paymentMethod: 'cash',
            link: '/transactions'
          });
        }
        if (t.transferAmount && t.transferAmount > 0) {
           items.push({
            id: t.id!,
            date: t.date,
            type: 'Venta (Transferencia)',
            description: `Venta por transferencia #${t.id}`,
            amount: t.transferAmount,
            isIncome: true,
            paymentMethod: 'transfer',
            link: '/transactions'
          });
        }
      }
    });

    // Add Purchases
    purchases.filter(p => p.storeId === activeStoreId && p.paymentStatus === 'paid').forEach(p => {
      const pDate = new Date(p.date);
      if (pDate >= start && pDate <= end) {
        items.push({
          id: p.id!,
          date: p.date,
          type: 'Compra',
          description: `Compra al contado #${p.id}`,
          amount: p.totalAmount,
          isIncome: false,
          paymentMethod: p.paymentMethod || 'cash',
          link: '/transactions'
        });
      }
    });

    // Add Expenses/Incomes
    expenses.filter(e => e.storeId === activeStoreId).forEach(e => {
      // Ignore expenses/incomes generated by sales, as they are already accounted for in the sale's cashAmount/transferAmount
      if (e.description.includes('en venta #') || e.description.includes('(Venta #')) {
        return;
      }

      const eDate = new Date(e.date);
      if (eDate >= start && eDate <= end) {
        items.push({
          id: e.id!,
          date: e.date,
          type: e.type === 'income' ? 'Ingreso' : 'Gasto',
          description: e.description,
          amount: e.amount,
          isIncome: e.type === 'income',
          paymentMethod: e.paymentMethod || 'cash',
          link: '/expenses'
        });
      }
    });

    return items.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
  }, [activeStoreId, transactions, expenses, purchases, dateRange]);

  const initialCash = treasuryRecord?.initialCapitalCash ?? treasuryRecord?.initialCapital ?? 0;
  const initialTransfer = treasuryRecord?.initialCapitalTransfer ?? 0;
  const initialTotal = initialCash + initialTransfer;
  
  // Calculate running balance for the period
  const periodIncomeCash = history.filter(h => h.isIncome && h.paymentMethod === 'cash').reduce((sum, h) => sum + h.amount, 0);
  const periodIncomeTransfer = history.filter(h => h.isIncome && h.paymentMethod === 'transfer').reduce((sum, h) => sum + h.amount, 0);
  
  const periodExpenseCash = history.filter(h => !h.isIncome && h.paymentMethod === 'cash').reduce((sum, h) => sum + h.amount, 0);
  const periodExpenseTransfer = history.filter(h => !h.isIncome && h.paymentMethod === 'transfer').reduce((sum, h) => sum + h.amount, 0);
  
  const currentCash = initialCash + periodIncomeCash - periodExpenseCash;
  const currentTransfer = initialTransfer + periodIncomeTransfer - periodExpenseTransfer;
  const currentTotal = currentCash + currentTransfer;

  if (!activeStoreId) {
    return (
      <div className="flex items-center justify-center h-[calc(100vh-8rem)]">
        <p className="text-gray-500 dark:text-slate-400 text-lg">Selecciona un punto de venta para ver la tesorería.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-bold text-gray-800 dark:text-slate-100">Tesorería y Caja</h2>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white dark:bg-[#161B22] p-6 rounded-xl shadow-sm border border-gray-100 dark:border-slate-800">
          <div className="flex justify-between items-start mb-4">
            <div className="w-full">
              <p className="text-sm font-medium text-gray-500 dark:text-slate-500 mb-1">Capital Inicial Total</p>
              {isEditingCapital ? (
                <div className="flex flex-col gap-2 mt-2">
                  <div className="flex items-center gap-2">
                    <Banknote className="w-4 h-4 text-gray-400 dark:text-slate-500" />
                    <input
                      type="number"
                      min="0"
                      step="0.01"
                      placeholder="Efectivo"
                      value={newCapitalCash}
                      onChange={(e) => setNewCapitalCash(e.target.value)}
                      className="w-full border border-gray-300 dark:border-slate-700 rounded-md px-2 py-1 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100"
                    />
                  </div>
                  <div className="flex items-center gap-2">
                    <CreditCard className="w-4 h-4 text-gray-400 dark:text-slate-500" />
                    <input
                      type="number"
                      min="0"
                      step="0.01"
                      placeholder="Transferencia"
                      value={newCapitalTransfer}
                      onChange={(e) => setNewCapitalTransfer(e.target.value)}
                      className="w-full border border-gray-300 dark:border-slate-700 rounded-md px-2 py-1 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500 bg-white dark:bg-slate-900 text-slate-900 dark:text-slate-100"
                    />
                  </div>
                  <div className="flex justify-end gap-2 mt-2">
                    <button onClick={() => setIsEditingCapital(false)} className="px-3 py-1 text-sm text-gray-600 dark:text-slate-400 hover:bg-gray-100 dark:hover:bg-slate-800 rounded">
                      Cancelar
                    </button>
                    <button onClick={handleSaveCapital} className="px-3 py-1 text-sm text-white bg-blue-600 hover:bg-blue-700 rounded">
                      Guardar
                    </button>
                  </div>
                </div>
              ) : (
                <div className="flex items-center justify-between">
                  <h3 className="text-2xl font-bold text-gray-900 dark:text-slate-100">{formatCurrency(initialTotal)}</h3>
                  {!isGuest ? (
                    <button onClick={startEditing} className="p-1 text-gray-400 dark:text-slate-500 hover:text-blue-600 dark:hover:text-blue-400 rounded transition-colors">
                      <Edit2 className="w-4 h-4" />
                    </button>
                  ) : (
                    <span className="text-gray-400 dark:text-slate-600 italic text-xs flex items-center gap-1">
                      <Lock className="w-3 h-3" /> Solo lectura
                    </span>
                  )}
                </div>
              )}
              {!isEditingCapital && (
                <div className="mt-3 space-y-1 text-sm">
                  <div className="flex justify-between text-gray-600 dark:text-slate-400">
                    <span className="flex items-center gap-1"><Banknote className="w-3 h-3" /> Efectivo:</span>
                    <span className="font-medium">{formatCurrency(initialCash)}</span>
                  </div>
                  <div className="flex justify-between text-gray-600 dark:text-slate-400">
                    <span className="flex items-center gap-1"><CreditCard className="w-3 h-3" /> Transf:</span>
                    <span className="font-medium">{formatCurrency(initialTransfer)}</span>
                  </div>
                </div>
              )}
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-[#161B22] p-6 rounded-xl shadow-sm border border-gray-100 dark:border-slate-800">
          <div className="flex justify-between items-start">
            <div className="w-full">
              <p className="text-sm font-medium text-gray-500 dark:text-slate-500 mb-1">Ingresos del Periodo</p>
              <h3 className="text-2xl font-bold text-green-600 dark:text-green-400">{formatCurrency(periodIncomeCash + periodIncomeTransfer)}</h3>
              <div className="mt-3 space-y-1 text-sm">
                <div className="flex justify-between text-gray-600 dark:text-slate-400">
                  <span className="flex items-center gap-1"><Banknote className="w-3 h-3" /> Efectivo:</span>
                  <span className="font-medium text-green-600 dark:text-green-400">+{formatCurrency(periodIncomeCash)}</span>
                </div>
                <div className="flex justify-between text-gray-600 dark:text-slate-400">
                  <span className="flex items-center gap-1"><CreditCard className="w-3 h-3" /> Transf:</span>
                  <span className="font-medium text-green-600 dark:text-green-400">+{formatCurrency(periodIncomeTransfer)}</span>
                </div>
              </div>
            </div>
            <div className="p-3 bg-green-50 dark:bg-green-900/20 rounded-lg ml-2">
              <ArrowUpRight className="w-6 h-6 text-green-600 dark:text-green-400" />
            </div>
          </div>
        </div>

        <div className="bg-white dark:bg-[#161B22] p-6 rounded-xl shadow-sm border border-gray-100 dark:border-slate-800">
          <div className="flex justify-between items-start">
            <div className="w-full">
              <p className="text-sm font-medium text-gray-500 dark:text-slate-500 mb-1">Egresos del Periodo</p>
              <h3 className="text-2xl font-bold text-red-600 dark:text-red-400">{formatCurrency(periodExpenseCash + periodExpenseTransfer)}</h3>
              <div className="mt-3 space-y-1 text-sm">
                <div className="flex justify-between text-gray-600 dark:text-slate-400">
                  <span className="flex items-center gap-1"><Banknote className="w-3 h-3" /> Efectivo:</span>
                  <span className="font-medium text-red-600 dark:text-red-400">-{formatCurrency(periodExpenseCash)}</span>
                </div>
                <div className="flex justify-between text-gray-600 dark:text-slate-400">
                  <span className="flex items-center gap-1"><CreditCard className="w-3 h-3" /> Transf:</span>
                  <span className="font-medium text-red-600 dark:text-red-400">-{formatCurrency(periodExpenseTransfer)}</span>
                </div>
              </div>
            </div>
            <div className="p-3 bg-red-50 dark:bg-red-900/20 rounded-lg ml-2">
              <ArrowDownRight className="w-6 h-6 text-red-600 dark:text-red-400" />
            </div>
          </div>
        </div>
      </div>

      <div className="bg-white dark:bg-[#161B22] rounded-xl shadow-sm border border-gray-100 dark:border-slate-800 overflow-hidden">
        <div className="p-6 border-b border-gray-100 dark:border-slate-800 flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
          <h3 className="text-lg font-bold text-gray-800 dark:text-slate-100">Historial de Operaciones</h3>
          
          <div className="flex items-center gap-4">
            <div className="flex items-center gap-2 bg-gray-50 dark:bg-slate-900 px-3 py-2 rounded-lg border border-gray-200 dark:border-slate-700">
              <Calendar className="w-4 h-4 text-gray-500 dark:text-slate-400" />
              <input
                type="date"
                value={dateRange.start}
                onChange={(e) => setDateRange(prev => ({ ...prev, start: e.target.value }))}
                className="bg-transparent border-none text-sm focus:ring-0 p-0 text-gray-700 dark:text-slate-300"
              />
              <span className="text-gray-400 dark:text-slate-600">-</span>
              <input
                type="date"
                value={dateRange.end}
                onChange={(e) => setDateRange(prev => ({ ...prev, end: e.target.value }))}
                className="bg-transparent border-none text-sm focus:ring-0 p-0 text-gray-700 dark:text-slate-300"
              />
            </div>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="bg-gray-50 dark:bg-slate-800/50 border-b border-gray-200 dark:border-slate-800">
                <th className="px-6 py-3 text-sm font-semibold text-gray-600 dark:text-slate-400">Fecha</th>
                <th className="px-6 py-3 text-sm font-semibold text-gray-600 dark:text-slate-400">Tipo</th>
                <th className="px-6 py-3 text-sm font-semibold text-gray-600 dark:text-slate-400">Descripción</th>
                <th className="px-6 py-3 text-sm font-semibold text-gray-600 dark:text-slate-400">Método</th>
                <th className="px-6 py-3 text-sm font-semibold text-gray-600 dark:text-slate-400 text-right">Monto</th>
                <th className="px-6 py-3 text-sm font-semibold text-gray-600 dark:text-slate-400 text-right">Acción</th>
              </tr>
            </thead>
            <tbody>
              {history.map((item, idx) => (
                <tr key={idx} className="border-b border-gray-100 dark:border-slate-800 last:border-0 hover:bg-gray-50 dark:hover:bg-slate-800/30 transition-colors">
                  <td className="px-6 py-4 text-sm text-gray-500 dark:text-slate-500">
                    {new Date(item.date).toLocaleString()}
                  </td>
                  <td className="px-6 py-4 text-sm">
                    <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                      item.isIncome ? 'bg-green-100 dark:bg-green-900/30 text-green-800 dark:text-green-300' : 'bg-red-100 dark:bg-red-900/30 text-red-800 dark:text-red-300'
                    }`}>
                      {item.type}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-sm text-gray-900 dark:text-slate-100">{item.description}</td>
                  <td className="px-6 py-4 text-sm text-gray-500 dark:text-slate-500">
                    {item.paymentMethod === 'cash' ? (
                      <span className="flex items-center gap-1"><Banknote className="w-4 h-4" /> Efectivo</span>
                    ) : (
                      <span className="flex items-center gap-1"><CreditCard className="w-4 h-4" /> Transferencia</span>
                    )}
                  </td>
                  <td className={`px-6 py-4 text-sm font-medium text-right ${item.isIncome ? 'text-green-600 dark:text-green-400' : 'text-red-600 dark:text-red-400'}`}>
                    {item.isIncome ? '+' : '-'}{formatCurrency(item.amount)}
                  </td>
                  <td className="px-6 py-4 text-sm text-right">
                    <Link to={item.link} className="inline-flex items-center gap-1 text-blue-600 dark:text-blue-400 hover:text-blue-800 dark:hover:text-blue-300 font-medium">
                      Ver <ExternalLink className="w-3 h-3" />
                    </Link>
                  </td>
                </tr>
              ))}
              {history.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-gray-500 dark:text-slate-500">
                    No hay operaciones en este rango de fechas.
                  </td>
                </tr>
              )}
            </tbody>
            <tfoot className="bg-gray-50 dark:bg-slate-800/50 border-t border-gray-200 dark:border-slate-800">
              <tr>
                <td colSpan={4} className="px-6 py-4 text-sm font-bold text-gray-900 dark:text-slate-100 text-right">
                  Balance Actual Total:
                </td>
                <td className="px-6 py-4 text-sm font-bold text-gray-900 dark:text-slate-100 text-right">
                  {formatCurrency(currentTotal)}
                </td>
                <td></td>
              </tr>
              <tr>
                <td colSpan={4} className="px-6 py-2 text-sm text-gray-600 dark:text-slate-400 text-right">
                  En Efectivo:
                </td>
                <td className="px-6 py-2 text-sm font-medium text-gray-900 dark:text-slate-100 text-right">
                  {formatCurrency(currentCash)}
                </td>
                <td></td>
              </tr>
              <tr>
                <td colSpan={4} className="px-6 py-2 text-sm text-gray-600 dark:text-slate-400 text-right">
                  En Transferencia:
                </td>
                <td className="px-6 py-2 text-sm font-medium text-gray-900 dark:text-slate-100 text-right">
                  {formatCurrency(currentTransfer)}
                </td>
                <td></td>
              </tr>
            </tfoot>
          </table>
        </div>
      </div>
    </div>
  );
}
